#!/bin/bash

STOPFILE="./stopfile"
rm -f $STOPFILE

if [ "$1" == "stop" ] ; then
    touch $STOPFILE
    exit
fi

TEMPDIR="/ramdisk/"

DESTHOST="seti-05"
DESTDIR="/ramdisk/"


function Log {
   echo "`date "+%Y%m%d-%H%M%S"`: ${1}"
 }


i=0
while [ `date "+%H%M"` -lt 1715 ] ; do
# while [ "$i" -lt 2 ] ; do
    FILENAME="pic_`date "+%Y%m%d-%H%M%S"`_$i.jpg"

    raspistill -ae 64,0xff,0x808000 -a 4 -a "Kollerberg %Y-%m-%d %X - $i" -o ${TEMPDIR}${FILENAME}
    Log "$FILENAME captured"

    timeout -k 10 -v 90 scp -q ${TEMPDIR}${FILENAME} ${DESTHOST}:${DESTDIR}
    Log "$FILENAME copied to server $DESTHOST."
    rm ${TEMPDIR}${FILENAME}
    Log "${FILENAME} removed"

    # ( cd ${DESTDIR} ; ln -s -f ${FILENAME} latest.jpg )

    if [ -e $STOPFILE ] ; then
        rm $STOPFILE
        Log "stopped by stopfile"
        exit
    fi

    i=$[$i+1]
done

Log "done for today"

# eof #

