#!/usr/bin/bash

MONTH=202504


for DAY in ${MONTH}?? ; do
    (
    cd ${DAY}
    VIDEO=kollerberg_${DAY}.mp4
    cat *.jpg | ffmpeg -f image2pipe -thread_queue_size 5000 -framerate 30 -i - -c:v libx264 -acodec copy -s 1296x972 $VIDEO

    )
done


# eof #

