#!/usr/bin/bash

/home/thomas/raspberry/seti/seti_rrd_graph.sh
/home/thomas/raspberry/pool/Ventilation_rrd_graph.sh
/home/thomas/raspberry/airparticulates/Airparticulates_rrd_graph.sh
/home/thomas/raspberry/weather/Weather_rrd_graph.sh

# eof #

