#!/bin/bash
#############################################################################
# Starts apps on various hosts.                                             #
# (c) https://github.com/thomaspfeiffer-git 2020, 2021                      #
#############################################################################

case "$HOSTNAME" in
    pid)
        ./start_apps_pid
        ;;
    nano02)
        ./start_apps_nano02
        ;;
    nano04)
        ./start_apps_nano04
        ;;
    nano05)
        ./start_apps_nano05
        ;;
    pik-i)
        ./start_apps_pik-i
        ;;
    pik-a)
        ./start_apps_pik-a
        ;;
    pik-k)
        ./start_apps_pik-k
        ;;
    pik-p)
        ./start_apps_pik-p
        ;;
    nuernberg)
        ./start_apps_nuernberg
        ;;
    *)
        echo "Unknown host '$HOSTNAME'."
        exit 1
esac

# eof #

