#!/bin/bash
#############################################################################
# Starts apps on pik-k                                                      #
# (c) https://github.com/thomaspfeiffer-git 2020                            #
#############################################################################

if [ $HOSTNAME != "pik-k" ] ; then
    echo "Wrong host! This script runs on pik-k only!"
    exit 1
fi


cd ~/raspberry/

cd kollerberg/
echo "Starting 'weather.py' ..."
nohup ./Weather_Kollerberg.py --sensor 2>&1 >weather_kollerberg.log &
cd ..

# eof #

