#!/bin/bash
#############################################################################
# Starts apps on pik-k                                                      #
# (c) https://github.com/thomaspfeiffer-git 2020, 2023                      #
#############################################################################

if [ $HOSTNAME != "pik-k" ] ; then
    echo "Wrong host! This script runs on pik-k only!"
    exit 1
fi


cd ~/raspberry/

cd kollerberg/
echo "Starting 'Weather_Kollerberg.py --sensor' ..."
nohup ./Weather_Kollerberg.py --sensor 2>&1 >weather_kollerberg.log &
cd ..


cd pool/
echo "Staring 'Circulation.py' ..."
sudo nohup ./Circulation.py --production 2>&1 > circulation.log &
cd ..


cd solarpower/
echo "Starting 'Solarpower.py' ..."
nohup ./Solarpower.py 2>&1 >solarpower.log &


# eof #

