#!/bin/bash
#############################################################################
# Starts apps on pik-i2                                                     #
# (c) https://github.com/thomaspfeiffer-git 2020, 2025                      #
#############################################################################

if [ $HOSTNAME != "pik-i2" ] ; then
    echo "Wrong host! This script runs on pik-i2 only!"
    exit 1
fi


cd ~/raspberry/

cd kollerberg/
echo "Starting 'weather.py' ..."
nohup ./Weather_Kollerberg.py --sensor 2>&1 >weather_kollerberg.log &
cd ..

# eof #

