#!/bin/bash
#############################################################################
# Starts apps on nano02                                                     #
# (c) https://github.com/thomaspfeiffer-git 2020                            #
#############################################################################

if [ $HOSTNAME != "nano02" ] ; then
    echo "Wrong host! This script runs on nano02 only!"
    exit 1
fi

cd /home/pi/raspberry/

cd weather/
echo "Starting 'Indoor.py --sensor' ..."
nohup ./Indoor.py --sensor 2>&1 > indoor.log &
cd ..

cd openweathermap/
echo "Starting 'openweather.py' ..."
nohup ./openweather.py > openweather.log 2>&1 &
cd ..

cd kollerberg/
echo "Starting 'Weather_Kollerberg.py --receiver_homeautomation' ..."
nohup ./Weather_Kollerberg.py --receiver_homeautomation 2>&1 >weather_kollerberg_homeautomation.log &
cd ..

# eof #

