#!/bin/bash
#############################################################################
# Starts apps on pik-k                                                      #
# (c) https://github.com/thomaspfeiffer-git 2020, 2023R, 2024               #
#############################################################################

if [ $HOSTNAME != "pik-k" ] ; then
    echo "Wrong host! This script runs on pik-k only!"
    exit 1
fi


cd ~/raspberry/

cd kollerberg/
echo "Starting 'Weather_Kollerberg.py --sensor' ..."
nohup ./Weather_Kollerberg.py --sensor 2>&1 >weather_kollerberg.log &
cd ..


cd pool/
echo "Staring 'Circulation.py' ..."
sudo nohup ./Circulation.py --production 2>&1 > circulation.log &

echo "Staring 'Circulation_Night.py' ..."
nohup ./Circulation_Night.py 2>&1 > circulation_night.log &
cd ..

cd power/
echo "Starting 'Solarpower.py' ..."
nohup ./Solarpower.py --sensor  2>solarpower.log >/dev/null &
cd ..


# eof #

