#!/bin/bash
#############################################################################
# Starts apps on pik-a                                                      #
# (c) https://github.com/thomaspfeiffer-git 2020                            #
#############################################################################

if [ $HOSTNAME != "pik-a" ] ; then
    echo "Wrong host! This script runs on pik-a only!"
    exit 1
fi


cd ~/raspberry/

cd kollerberg/
echo "Starting 'weather.py' ..."
nohup ./Weather_Kollerberg.py --sensor 2>&1 >weather_kollerberg.log &
cd ..

cd airparticulates/
echo "Starting 'Airparticulates.py' ..."
nohup ./Airparticulates.py --sensor 2 2>&1 > airparticulates.log &
cd ..

# eof #

