#!/bin/bash
#############################################################################
# Starts apps on nano04                                                     #
# (c) https://github.com/thomaspfeiffer-git 2020                            #
#############################################################################

if [ $HOSTNAME != "nano04" ] ; then
    echo "Wrong host! This script runs on nano04 only!"
    exit 1
fi

cd /home/pi/raspberry/

cd weather/
echo "Starting 'Outdoor.py --sensor' ..."
nohup ./Outdoor.py --sensor 2>&1 > outdoor.log &
cd ..

cd airparticulates/
echo "Starting 'Airparticulates.py --sensor' ..."
nohup ./Airparticulates.py --sensor 1 2>&1 > airparticulates.log &
cd ..

# eof #

