#!/bin/bash
#############################################################################
# check_network                                                             #
# (c) https://github.com/thomaspfeiffer-git/raspberry, 2019                 #
#############################################################################

# useful links
# https://askubuntu.com/questions/811733/how-can-i-restart-my-wi-fi-connection-from-the-command-line

# https://github.com/volumio/Volumio2/issues/1462
# https://github.com/raspberrypi/linux/issues/1342



/sbin/ifconfig wlan0 | grep "inet " 2>&1 >/dev/null

if [ $? -eq 0 ] ; then
    echo -n "`date` - "
    echo "Network checked: ok."
else
    echo -n "`date` - "
    echo "Restarting network ..."

    if [ $(uname -a | grep armv7l | wc -l) == "1" ] ; then  # NanoPi
        systemctl restart NetworkManager
        sleep 5
        /etc/init.d/networking restart
        sleep 5
        systemctl restart NetworkManager
    else            # Raspberry
        /etc/init.d/networking restart
    fi
fi

# eof #

