#!/bin/bash
#############################################################################
# check_network                                                             #
# (c) https://github.com/thomaspfeiffer-git/raspberry, 2019, 2025           #
#############################################################################

# useful links
# https://askubuntu.com/questions/811733/how-can-i-restart-my-wi-fi-connection-from-the-command-line

# https://github.com/volumio/Volumio2/issues/1462
# https://github.com/raspberrypi/linux/issues/1342




# /sys/firmware/devicetree/base/model
# - Raspberry Pi 3 Model B Rev 1.2
# - FriendlyARM NanoPi NEO Air

/sbin/ifconfig wlan0 | grep "broadcast" 2>&1 >/dev/null

if [ $? -eq 0 ] ; then
    echo -n "`date` - "
    echo "Network checked: ok."
else
    echo -n "`date` - "
    echo "Restarting network ..."


    # todo
    # echo $(tr -d '\0' < /sys/firmware/devicetree/base/model)
    # avoids warning of null byte in string

    if [ $( echo $( cat /sys/firmware/devicetree/base/model )  | grep Rasp | wc -l) == "1" ] ; then

        echo "Restarting network Raspi"
        sudo service NetworkManager restart

        # next try:
        # sudo nmcli radio wifi off
        # sleep 5
        # sudo nmcli radio wifi on

        # old:
        # sudo service networking restart
        # sudo wpa_cli -i wlan0 reconfigure
        # sudo systemctl restart wpa_supplicant.service
        # sudo systemctl restart dhcpcd.service
        # sudo ifdown --force wlan0
        # sleep 5
        # sudo ifup wlan0
    else
        systemctl restart NetworkManager
        sleep 5
        systemctl restart NetworkManager
    fi
fi

# eof #

