#!/bin/bash
#############################################################################
# check_network                                                             #
# (c) https://github.com/thomaspfeiffer-git/raspberry, 2019                 #
#############################################################################

ifconfig wlan0 | grep "inet " 2>&1 >/dev/null

if [ $? -eq 0 ] ; then 
    echo -n "`date` - "
    echo "Network checked: ok."
else
    echo -n "`date` - "
    echo "Restarting network ..."
    systemctl restart NetworkManager
fi

# eof #

