#!/usr/bin/bash
# update/upgrade script
# (c) https://github.com/thomaspfeiffer-git 2023
################################################

sudo apt-get update -y --fix-missing
sudo apt-get upgrade -y --fix-missing

sudo apt-get clean -y

sudo apt-get autoremove -y

sudo checkrestart

# eof #

